######################################################################
# Automatically generated by qmake (2.01a) ?? 31. ??? 22:03:56 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
